---
name: "Super-Linter"

on:
  push:

jobs:
  linting:
    name: super-linter
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          # Full git history is needed
          fetch-depth: 0

      - name: Create reporting dir
        run: mkdir -p super-linter.report

      - name: Run super-linter
        uses: github/super-linter/slim@v5
        env:
          DEFAULT_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # limit to new and updated files
          VALIDATE_ALL_CODEBASE: false
